<?php

// Create a global array for all the endpoints
//$end_point_list = array();

/**
 * Islandora menu hook
 * @return string 
 */
function islandora_services_menu() {

    // Create an array to return
    $items = array();

    // Display all endpoints page
    $items['islandora_services/list'] = array(
        'title' => 'Islandora Services List',
        'page callback' => 'islandora_services_list_page',
        'access arguments' => array('view'),
        'type' => MENU_NORMAL_ITEM
    );

    // Create a global list of all the services
    $services = module_invoke_all('register_services');
    
    // Store the list for later use
    variable_set('islandora_services', $services);
    
    // Loop through all the modules to get endpoints
    foreach($services as $module => $endpoints) {
        
        // Loop through all the end points to get the parameters
        foreach($endpoints as $endpoint => $params) {
                
            // Register an end point with drupal
            $items['islandora_services/'. $module ."/". $endpoint] = array(
                'title' => $params['title'],
                'page callback' => 'islandora_service_handler',
                'page arguments' => array($module, $endpoint),
                'access arguments' => $params['security'],
                'type' => MENU_CALLBACK
            );
        }
    }

    // Return the link
    return $items;
}

function islandora_services_list_page() {

    // Create the return element
    $content = null;

    $header = array('Module', "End Point", "Title", "Callback", "Render In Drupal", "Example");
    $rows = array();
    $services = variable_get('islandora_services', NULL);

    // Loop through all the modules to get endpoints
    foreach($services as $module => $endpoints) {
        
        // Loop through all the end points to get the parameters
        foreach($endpoints as $endpoint => $params) {
            
            $render = "False";
            if ( $params['render_drupal'] == true ) {
                $render = "True";
            }
            
            // Create the data row to be added to the table
            $row = array($module, $endpoint, $params['title'], $params['function'], $render, $module . '/' . $params['example']);
            
            // Add it to the table
            $rows[] = $row;
        }
    }
    // Create a table and add it to the render list
    $content .= theme_table($header, $rows);
    
    // Return the content for render
    return $content;
}

function islandora_service_handler() {

    // Get the arguments
    $args = func_get_args();

    // Check to make sure we have the module and endpoint parameters
    if ( count($args) < 2 )
    {
        var_dump($args);
        return "Malformed endpoint";
    }    
    
    // Get the list of services
    $services = variable_get('islandora_services', NULL);
    
    // Create the results to be displayed
    $results = null;

    // Pop the module and endpoint of the front of the list
    $module = array_shift($args);
    $endpoint = array_shift($args);
    
    // Get the details of the end 
    $param_count = $services[$module][$endpoint]['param_count'];
    $function = $services[$module][$endpoint]['function'];
    $render_drupal = $services[$module][$endpoint]['render_drupal'];
        
    // Check the param count
    if ( $param_count != count($args) ) {
        return "Parameter count doesn't match!";
    }
        
    //$results = module_invoke($module, $function, $args);
    $results = call_user_func_array($module.'_'.$function, $args);
    
    if ( $render_drupal == true ) {
        return $results;
    } else {
        echo $results;
    }
}

/**
 * Example register endpoints hook
 * @return type 
 */
function islandora_services_register_services()
{
    // Define the end points
    return array(
        'islandora_services' => array (
            'myendpoint' => array (
                'title' => 'test callback', 
                'function' => 'myendpoint_handler', 
                'param_count' => 1, 
                'security' => array('access content'),
                'render_drupal' => false, 
                'example' => 'myendpoint/{value}',
            ),
            'myendpoint2' => array (
                'title' => 'test callback2',
                'function' => 'myendpoint_handler2',
                'param_count' => 2,
                'security' => array('access content'),
                'render_drupal' => true,
                'example' => 'myendpoint/{value1}/{value2}',
            ),
        )
    );
}

/**
 * Example callback
 * @param type $param 
 */
function islandora_services_myendpoint_handler($param) {
    $results = "islandora_services_myendpoint_handler(".$param.");";
    return $results;
}

/**
 * Example callback
 * @param type $param 
 */
function islandora_services_myendpoint_handler2($param, $param2) {
    $results = "islandora_services_myendpoint_handler(".$param.",".$param2.");";
    return $results;
}
